# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "clairvoyant" do |cv_vm|
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Clairvoyant VM" + Time.now.strftime(" %Y-%m-%d")
    vb.gui = true
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["storageattach", :id, 
                "--storagectl", "IDE Controller", 
                "--port", "0", "--device", "0", 
                "--type", "dvddrive", 
                "--medium", "emptydrive"]    
    vb.customize ["modifyvm", :id, "--vram", "32"]

  end
  config.vm.synced_folder '.', '/vagrant', disabled: true  
  config.vm.hostname = "epl"
  config.vm.network "forwarded_port", host: 2222, guest: 22
  config.vm.provision "shell", path: "root-bootstrap.sh"
  config.vm.provision "shell", privileged: false, path: "user-bootstrap.sh"
end

